<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #111; }
        .wrap { padding: 24px; }
        .card { border: 1px solid #ddd; border-radius: 8px; padding: 20px; }
        .row { display: flex; justify-content: space-between; margin: 8px 0; }
        .muted { color: #666; font-size: 12px; }
        .title { font-weight: 700; font-size: 18px; margin-bottom: 8px; }
        .amount { font-weight: 700; font-size: 22px; }
        .badge { display: inline-block; padding: 6px 10px; border-radius: 999px; font-size: 12px; }
        .badge-success { background: #dcfce7; color: #166534; }
        .badge-pending { background: #ffedd5; color: #9a3412; }
        .badge-failed { background: #fee2e2; color: #991b1b; }
        hr { border: none; border-top: 1px solid #e5e7eb; margin: 12px 0; }
        .header { display:flex; align-items:center; gap:12px; }
        .logo { max-height: 40px; }
        .header svg { height: 40px; display: inline-block; }
        .footer { position: fixed; bottom: 16px; left: 24px; right: 24px; font-size: 12px; color: #666; display:flex; justify-content: space-between; }
        .page:after { content: counter(page) " / " counter(pages); }
    </style>
</head>
<body>
<div class="wrap">
    <div class="card">
        <div class="row">
            <div>
                <div class="header">
                    @if($gdAvailable)
                        <img class="logo" src="{{ public_path('images/primarylogo.png') }}" alt="{{ config('app.name') }}">
                    @endif
                    <div>
                        <div class="title">{{ config('app.name') }}</div>
                        <div class="muted">Invoice</div>
                    </div>
                </div>
            </div>
            <div>
                <div class="muted">Date: {{ $date }}</div>
                <div class="muted">Ref: {{ $ref }}</div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div>
                <div class="muted">Billboard</div>
                <div>{{ $title }}</div>
            </div>
            <div>
                <div class="muted">Period</div>
                <div>{{ $start && $end ? ($start.' → '.$end) : '-' }}</div>
            </div>
        </div>
        <div class="row">
            <div>
                <div class="muted">Duration</div>
                <div>{{ $duration ? $duration.' days' : '-' }}</div>
            </div>
            <div>
                <div class="muted">Status</div>
                <div class="badge {{ $payment->status==='success' ? 'badge-success' : (($payment->status==='pending'||$payment->status==='initialized') ? 'badge-pending' : 'badge-failed') }}">{{ ucfirst($payment->status) }}</div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="muted">Total Amount</div>
            <div class="amount">₦{{ $amount }}</div>
        </div>
        <div class="row">
            <div class="muted">Platform Commission (10%)</div>
            <div>₦{{ $companyCommission }}</div>
        </div>
        <div class="row">
            <div class="muted">Owner Earnings (90%)</div>
            <div>₦{{ $loapAmount }}</div>
        </div>
    </div>
    <div class="muted" style="margin-top: 8px;">Generated by {{ config('app.name') }}</div>
    </div>
<div class="footer">
    <div>{{ config('app.name') }} • {{ url('/') }}</div>
    <div class="page"></div>
    <div>© {{ date('Y') }} {{ config('app.name') }}</div>
</div>
</body>
</html>
